#!/bin/bash

source settings
source constants

username=$1; shift
password=$1; shift

bash account-make $username $password
result=`bash editprofile-namer $username $password`
result=`bash photo-uploader $username $password`
result=`bash notifications-fix $username $password`


