#!/bin/bash

source settings
source constants

username=$1; shift
password=$1; shift

firstname=$1; shift # firstname
lastname=$1; shift # lastname
birthmonth=$1; shift # 04
birthday=$1; shift # 10
birthyear=$1; shift # 1993
gender=$1; shift # f
country=$1; shift # PH
mobilephone=$1; shift # +63.

cookies=$username

curl_verify="-F _submitted=1 -F introduce= -F pp_invite= -F invite= -F inviteref= -F next=/regnewphoto.php?sc=1516 -F email=$username -F password1=$password -F password2=$password -F firstname=${firstname:-$DEFAULT_FIRSTNAME} -F lastname=${lastname:-$DEFAULT_LASTNAME} -F birthmonth=${birthmonth:-$DEFAULT_BIRTHMONTH} -F birthday=${birthday:-$DEFAULT_BIRTHDAY} -F birthyear=${birthyear:-$DEFAULT_BIRTHYEAR} -F gender=${gender:-$DEFAULT_GENDER} -F country=${country:-$DEFAULT_COUNTRY} -F mobilephone=${mobilephone:-$DEFAULT_MOBILEPHONE}"

result=`curl -c $cookies "$URL_VERIFY"`
curl -b $cookies "$URL_JOIN" $curl_verify -L


