#!/bin/bash

source settings
source constants

username=$1; shift
password=$1; shift
uids=$@; shift

cookies=$username

function page-browse
{
	url=$1; shift
	param=$1; shift

	bash page-browse $username $password $url $param	
}

for uid in $uids
{
	page-browse "$URL_PROFILE/$uid" "--head"
	
	if [ "$ERRORS" -eq "0" ]
		then
		$MYSQL_STRING -e "insert into crawled (uid, browsed) values ('$uid', now()) on duplicate key update browsed = now();"
	fi	

	ERRORS=0
}


