#!/bin/bash

source settings
source constants

override=$@;

while [ 0 ]
do
	if [ ! "$override" ]
	then
		#batches=`$MYSQL_STRING -N -e "select distinct(batch) from bots where batch <> 'batch';"`
		batches=`$MYSQL_STRING -N -e "select distinct(batch) from apps where batch <> 'batch';"`
	else
		batches=($override)
	fi

	for batch in $batches
	{
		installer_emails=`$MYSQL_STRING -N -e "select email from bots where type='installer' and status = '' and batch = '$batch';"`
		crawler_emails=`$MYSQL_STRING -N -e "select email from bots where type='crawler' and status = '' and batch = '$batch';"`

		url_apps=(`$MYSQL_STRING -N -e "select url from apps where batch = '$batch';"`)


		for installer_email in $installer_emails
		{
			installer_password=`$MYSQL_STRING -N -e "select password from bots where email = '$installer_email';"`

			result=`bash page-browse $installer_email $installer_password $URL_WIDGET_MANAGE -L`

			raw_api_keys=`echo $result | grep -oP '\?api_key=(.+?)\"'`

			if [ "$raw_api_keys" ]
			then
				for raw_api_key in $raw_api_keys
				{
					api_key=`echo ${raw_api_key#*api_key=}`
					api_key=`echo ${api_key%\"}`

					result=`bash page-browse $installer_email $installer_password $URL_WIDGET_INFO?api_key=$api_key -L`

					api_secret=`echo $result | grep -oP 'id="api_secret" value="(.+?)"'`
					api_secret=`echo ${api_secret#*value=\"}`
					api_secret=`echo ${api_secret%\"}`

					id=`echo $result | grep -o -P 'id="id" value="(.+?)"'`
					id=`echo ${id#*value=\"}`
					id=`echo ${id%\"}`

					if [ "$url_apps" ]
					then
						url_xml_activate=${url_apps[0]}
						#app_title=`$MYSQL_STRING -N -e "select title from apps where url = '$url_xml_activate' and batch = '$batch';"`
						app_title=`$MYSQL_STRING -N -e "select md5(now());"`

						unset url_apps[0]
						url_apps=( "${url_apps[@]}" ) # shift

						test_url_xml_activate=`echo $result | grep -oP $url_xml_activate`

						if [ ! "$test_url_xml_activate" ]
						then

							curl_activate="-F api_key=$api_key -F api_secret=$api_secret -F id=$id -F type= -F name=$app_title -F os_url=$url_xml_activate -F category=2 -F description= -F display_name= -F display_to_profile=Yes -F action=edit";

							result=`bash page-browse $installer_email $installer_password $URL_WIDGET_INFO $curl_activate -L`
						fi
					fi

					for crawler_email in $crawler_emails
					{
						crawler_password=`$MYSQL_STRING -N -e "select password from bots where email = '$crawler_email' and batch = '$batch';"`
						crawler_url=`$MYSQL_STRING -N -e "select url from bots where email = '$crawler_email' and batch = '$batch';"`

						result=`bash page-browse $installer_email $installer_password $crawler_url -L`

						test_api_key=`echo $result | grep -oP $api_key`

						if [ ! "$test_api_key" ]
						then
							result=`bash widget-install $crawler_email $crawler_password $api_key`
						fi					
					}			
				}
			else
				bash user-login $installer_email $installer_password
				break
			fi

			break
		}
	}
	sleep $SLEEP_WIDGET_INSTALLER
done

